adventureworks:
  target: postgres
  outputs:

    postgres:
      type: postgres
      host: postgres
      port: "{{ env_var('POSTGRES_PORT') | int }}" # jinja filter to convert string to int
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}" 
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: dbt_dev
      threads: 12