adventureworks:
  target: duckdb
  outputs:

    postgres:
      type: postgres
      host: localhost
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}" 
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: dbo
      threads: 12