name: tr-dbt-dimensional

services:
  db:
    image: postgres:17
    container_name: tr-dbt-dimensional-postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres} -h 127.0.0.1 -p ${POSTGRES_PORT:-5432}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: