services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: ${LOCAL_UID:-1000}
        USER_GID: ${LOCAL_GID:-1000}
        ENABLE_GUI: "false"   # 本番はGUIなし
    env_file:
      - ./.env
    working_dir: /workspace/project
    depends_on:
      - db
    networks:
      - metanet1
    # 本番は bind mount なし（イミュータブル）

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    # 本番はFW/リバプロで制御するなら ports を外してもOK
    ports:
      - "5432:5432"
    networks:
      - metanet1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres} -h 127.0.0.1 -p ${POSTGRES_PORT:-5432}"]
      interval: 5s
      timeout: 3s
      retries: 10


  metabase:
    image: metabase/metabase:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy # db が healthy になるまで待つ
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB:-metabase_appdb}
      MB_DB_HOST: db
      MB_DB_PORT: ${POSTGRES_PORT:-5432}
      MB_DB_USER: ${POSTGRES_USER:-metabase_user}
      MB_DB_PASS: ${POSTGRES_PASSWORD:-change_me}
    networks:
      - metanet1
    ports:
      - "3000:3000"

networks:
  metanet1:
    driver: bridge

volumes:
  pgdata: