[project]
name = "tr-dbt-dimensional"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "dbt-core>=1.10.4",
    "dbt-duckdb>=1.9.4",
    "sqlfluff>=3.4.2",
    "sqlfluff-templater-dbt>=3.4.2",
]
