defaults:
  encoding: utf-8
  skiprows: 0
  chunksize: 200000
  filename_glob: "*.csv"

tables:
  links:
    folder: namespace=ingest_test/table=links
    primary_key: ["movieId"]

  movies:
    folder: namespace=ingest_test/table=movies
    primary_key: ["movieId"]

  ratings:
    folder: namespace=ingest_test/table=ratings
    primary_key: ["userId", "movieId"]

  tags:
    folder: namespace=ingest_test/table=tags
    primary_key: ["userId", "movieId", "timestamp"]
    