defaults:
  encoding: utf-8
  chunksize: 200000
  filename_glob: "*.csv"
  load_mode: upsert # or replace
  skiprows: 0

tables:
  links:
    folder: namespace=ingest_test/table=links
    primary_key: ["movieId"]
    load_mode: replace
    replace_keys: ["date", "name"] # load_mode=replace のとき必須

  movies:
    folder: namespace=ingest_test/table=movies
    primary_key: ["movieId"]

  ratings:
    folder: namespace=ingest_test/table=ratings
    primary_key: ["userId", "movieId"]

  tags:
    folder: namespace=ingest_test/table=tags
    primary_key: ["userId", "movieId", "timestamp"]
    # 例: 常に1行メタがあると分かっているなら上書き
    # skiprows: 1