defaults:
  encoding: utf-8
  skiprows: auto        # ← 自動検出にしたい場合。無指定でも可
  chunksize: 200000
  filename_glob: "*.csv"

tables:
  links:
    folder: namespace=ingest_test/table=links
    primary_key: ["movieId"]

  movies:
    folder: namespace=ingest_test/table=movies
    primary_key: ["movieId"]

  ratings:
    folder: namespace=ingest_test/table=ratings
    primary_key: ["userId", "movieId"]

  tags:
    folder: namespace=ingest_test/table=tags
    primary_key: ["userId", "movieId", "timestamp"]
    # 例: 常に1行メタがあると分かっているなら上書き
    # skiprows: 1