services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    ports:
      - "8000:8000"  # Change this port as needed for your application.

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped 
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  superset:
    build:
      context: .
      dockerfile: superset.Dockerfile
    image: apache/superset:custom
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - "8088:8088"  # Change this port as needed for Superset.
    environment:
      SUPERSET_DATABASE_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SUPERSET_HOME: /app/superset_home
      SUPERSET_CONFIG_PATH: /app/superset_home/superset_config.py
    volumes:
      - superset-data:/app/superset_home
      - ../superset_config.py:/app/superset_home/superset_config.py
    healthcheck:
      disable: true  # Disable healthcheck to avoid issues with Superset startup.
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  superset-init:
    image: apache/superset:custom
    volumes:
      - superset-data:/app/superset_home
    restart: "no"
    depends_on:
      superset:
        condition: service_started
    env_file:
      - ../.env
    entrypoint: >
      /bin/bash -c "
        superset db upgrade &&
        superset fab create-admin \
          --username admin \
          --firstname Superset \
          --lastname Admin \
          --email egwats@gmail.com \
          --password ${SUPERSET_ADMIN_PASSWORD:-admin} &&
        superset init
      "

volumes:
  postgres-data:
  superset-data:
    # Use named volumes to persist data across container restarts.



#   metabase:
#     image: metabase/metabase:latest
#     restart: unless-stopped
#     depends_on:
#       - db
#     env_file:
#       - ../.env
#     ports:
#       - "3000:3000"  # Change this port as needed for Metabase.
#     environment:
#       MB_DB_TYPE: postgres
#       MB_DB_HOST: db
#       MB_DB_PORT: 5432
#       MB_DB_USER: ${POSTGRES_USER}
#       MB_DB_PASS: ${POSTGRES_PASSWORD}
#       MB_DB_DBNAME: ${POSTGRES_DB}
#     volumes:
#       - metabase-data:/metabase-data

