services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    ports:
      - "8000:8000"  # Change this port as needed for your application.

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)



  db:
    image: postgres:latest
    env_file:
      - ../.env
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  superset:
    build:
      context: .
      dockerfile: superset.Dockerfile
    image: apache/superset:custom
    env_file:
      - ../.env
    environment:
      SUPERSET_DATABASE_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SUPERSET_HOME: /app/superset_home
      SUPERSET_CONFIG_PATH: /app/superset_home/superset_config.py
    volumes:
      - superset-data:/app/superset_home
      - ../superset_config.py:/app/superset_home/superset_config.py:ro
    ports:
      - "8088:8088"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      disable: true

  superset-init:
    image: apache/superset:custom
    env_file:
      - ../.env
    environment:
      # → superset と同じ DATABASE_URI を必ず指定
      SUPERSET_DATABASE_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SUPERSET_HOME: /app/superset_home
      SUPERSET_CONFIG_PATH: /app/superset_home/superset_config.py
    volumes:
      - superset-data:/app/superset_home
      - ../superset_config.py:/app/superset_home/superset_config.py:ro
    entrypoint:
      - /bin/bash
      - -c
      - |
        superset db upgrade &&
        superset fab create-admin \
          --username ${SUPERSET_ADMIN_USER:-admin} \
          --firstname Superset \
          --lastname Admin \
          --email egwats@gmail.com \
          --password ${SUPERSET_ADMIN_PASSWORD:-admin} &&
        superset init
    depends_on:
      superset:
        condition: service_started
    restart: "no"

volumes:
  postgres-data:
  superset-data: